### ISSUE TITLE
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by lylet-AC** [RLBot/RLBotPythonExample#17]
Followed the guide and I have python 3.6.5 installed. I start rocket league and run the run-gui.bat file.  It injects the dll, waits for it to load and then crashes.

![error](https://user-images.githubusercontent.com/31486141/49402439-e3071200-f717-11e8-9f9c-f6a5bf372907.png)

**Comment by Vulcanostrol** [comment]
Make sure you have the very newest RLBot version, it was updated minutes ago

**Comment by tarehart** [comment]
He does have the newest, it's there in the screenshot. Let's take this discussion to discord, it'll be easier!

**Comment by lylet-AC** [comment]
Start button?  Sorry, do you mean the run-gui.bat?  If I run it again it does the same thing.  I've been trying to fix this error for about 2 hours, but I haven't had a successful solution.  I've tried reinstalling python and using the java bot instead, but that uses the same python interface so it did the same thing.

**Comment by tarehart** [comment]
I'm a bit confused because run-gui.bat is intended to open a GUI and not attempt dll injection until you click the big start button. Your screenshot shows logs from a dll injection.

But, if you tried twice without closing rocket league in between, then you've essentially already tried what I was suggesting. I have no other ideas at the moment.

**Comment by lylet-AC** [comment]
Ah, if I try to hit Run again the program hangs on the crash.

**Comment by tarehart** [comment]
Fixed by ccman and skyborg in https://github.com/RLBot/RLBot/pull/302
